from PyQt5.QtWidgets import QMainWindow, QDialog, QMessageBox
from mainGUI import Ui_MainWindow


class LogFileAnalysis(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.show()
        self.RightPayloadlabel.hide()
        self.RightPayloadpushButton.hide()
        self.RightPayloadtextEdit.hide()
        self.ParameterLeftPayloadlabel.setEnabled(False)
        self.ParameterLeftPayloadtableView.setEnabled(False)
        self.ParameterRightPayloadlabel.setEnabled(False)
        self.ParameterRightPayloadtableView.setEnabled(False)
        self.label.setEnabled(False)
        self.label_2.setEnabled(False)
        self.label_3.setEnabled(False)
        self.LeftPayloadParameterCountlabel.setEnabled(False)
        self.RightPayloadParameterCountlabel.setEnabled(False)
        self.label_8.setEnabled(False)
        self.LeftMisCountlabel.setEnabled(False)
        self.RightMisCountlabel.setEnabled(False)
        self.label_11.setEnabled(False)
        self.CommonCountlabel.setEnabled(False)
        self.CommonParameterpushButton.setEnabled(False)
        self.MisMatchedParameterpushButton.setEnabled(False)
        self.AllParameterpushButton.setEnabled(False)

        self.RequestParameterlabel.setEnabled(True)
        self.RequestParametertextEdit.setEnabled(True)
        self.ResponseAcknowledgementlabel.setEnabled(True)
        self.ResponseAcknowledgementtextEdit.setEnabled(True)
        self.ResponseCompletedlabel.setEnabled(True)
        self.ResponseCompletedtextEdit.setEnabled(True)
        self.AnonymousParameterlabel.setEnabled(True)
        self.AnonymousParametertextEdit.setEnabled(True)

        self.GetParameterListpushButton.show()
        self.ComparePayloadpushButton.hide()
        self.GetParameterradioButton.clicked.connect(self.get_parameter_list)
        self.CompareParameterradioButton.clicked.connect(self.compare_payload)

    def get_parameter_list(self):
        self.RightPayloadlabel.hide()
        self.RightPayloadpushButton.hide()
        self.RightPayloadtextEdit.hide()
        self.ParameterLeftPayloadlabel.setEnabled(False)
        self.ParameterLeftPayloadtableView.setEnabled(False)
        self.ParameterRightPayloadlabel.setEnabled(False)
        self.ParameterRightPayloadtableView.setEnabled(False)
        self.label.setEnabled(False)
        self.label_2.setEnabled(False)
        self.label_3.setEnabled(False)
        self.LeftPayloadParameterCountlabel.setEnabled(False)
        self.RightPayloadParameterCountlabel.setEnabled(False)
        self.label_8.setEnabled(False)
        self.LeftMisCountlabel.setEnabled(False)
        self.RightMisCountlabel.setEnabled(False)
        self.label_11.setEnabled(False)
        self.CommonCountlabel.setEnabled(False)
        self.CommonParameterpushButton.setEnabled(False)
        self.MisMatchedParameterpushButton.setEnabled(False)
        self.AllParameterpushButton.setEnabled(False)
        self.GetParameterListpushButton.show()
        self.ComparePayloadpushButton.hide()
        self.RequestParameterlabel.setEnabled(True)
        self.RequestParametertextEdit.setEnabled(True)
        self.ResponseAcknowledgementlabel.setEnabled(True)
        self.ResponseAcknowledgementtextEdit.setEnabled(True)
        self.ResponseCompletedlabel.setEnabled(True)
        self.ResponseCompletedtextEdit.setEnabled(True)
        self.AnonymousParameterlabel.setEnabled(True)
        self.AnonymousParametertextEdit.setEnabled(True)

    def compare_payload(self):
        self.RightPayloadlabel.show()
        self.RightPayloadpushButton.show()
        self.RightPayloadtextEdit.show()
        self.ParameterLeftPayloadlabel.setEnabled(True)
        self.ParameterLeftPayloadtableView.setEnabled(True)
        self.ParameterRightPayloadlabel.setEnabled(True)
        self.ParameterRightPayloadtableView.setEnabled(True)
        self.label.setEnabled(True)
        self.label_2.setEnabled(True)
        self.label_3.setEnabled(True)
        self.LeftPayloadParameterCountlabel.setEnabled(True)
        self.RightPayloadParameterCountlabel.setEnabled(True)
        self.label_8.setEnabled(True)
        self.LeftMisCountlabel.setEnabled(True)
        self.RightMisCountlabel.setEnabled(True)
        self.label_11.setEnabled(True)
        self.CommonCountlabel.setEnabled(True)
        self.CommonParameterpushButton.setEnabled(True)
        self.MisMatchedParameterpushButton.setEnabled(True)
        self.AllParameterpushButton.setEnabled(True)
        self.GetParameterListpushButton.hide()
        self.ComparePayloadpushButton.show()
        self.RequestParameterlabel.setEnabled(False)
        self.RequestParametertextEdit.setEnabled(False)
        self.ResponseAcknowledgementlabel.setEnabled(False)
        self.ResponseAcknowledgementtextEdit.setEnabled(False)
        self.ResponseCompletedlabel.setEnabled(False)
        self.ResponseCompletedtextEdit.setEnabled(False)
        self.AnonymousParameterlabel.setEnabled(False)
        self.AnonymousParametertextEdit.setEnabled(False)



